services:
  fvdb-dev:
    build:
      context: ../
      dockerfile: fvdb/Dockerfile

    command: sleep infinity
    volumes:
      - ../:/openvdb
      # --- SSH Agent Forwarding ---
      # Mount the SSH agent socket from your host into the container.
      # The devcontainer extension automatically resolves ${SSH_AUTH_SOCK} on the host.
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /tmp/ssh-agent.sock

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # --- SSH Agent Forwarding ---
      # Tell tools inside the container where to find the agent socket.
      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
