name: fvdb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - clang-format=18
  - clang-tools=18
  - clang=18
  - cmake
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=13.0
  - cxx-compiler
  - gcc_linux-64=14.2
  - gh
  - git
  - gitpython
  - gxx_linux-64=14.2
  - ipython
  - ipykernel
  - jupyterlab
  - libclang
  - libcublas-dev
  - libcurand-dev
  - libcusolver-dev
  - libcusparse-dev
  - libpng
  - linkify-it-py
  - make
  - matplotlib
  - msgpack-python
  - myst-parser
  - nbmake
  - ninja
  - numpy
  - openssl
  - openusd
  - pandas
  - parameterized
  - pip
  - pkg-config
  - polyscope
  - psutil
  - pybind11
  - py-opencv>=4.10[build=headless*]
  - pyrender
  - pytest-benchmark
  - python=3.13
  - pytorch-gpu=2.10.0
  - rich
  - seaborn
  - scikit-build-core
  - setuptools>=68.2.2
  - sparsehash
  - sphinx_rtd_theme
  - sphinx>=7.0.0
  - tensorboard
  - tqdm
  - zlib
    ## 3dgs
  - gdal
  - pillow
  - pyproj
  - pyyaml
  - scikit-learn
  - srt
  - torchvision
  - tyro
  - utm
  - viser
  - pip:
    - point-cloud-utils
    - pytest-markdown-docs
    - https://fvdb-packages.s3.us-east-2.amazonaws.com/dev-whls/pt210cu130/torchsparse-2.1.0-cp312-cp312-linux_x86_64.whl
    - https://fvdb-packages.s3.us-east-2.amazonaws.com/dev-whls/pt210cu130/torch_scatter-2.1.2-cp312-cp312-linux_x86_64.whl
    ## 3dgs tests
    - dlnr_lite
    - einops
    - oiio-static-python
