name: fvdb_min
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - cmake
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-nvrtc-dev
  - cuda-nvtx-dev
  - cuda-version=12.8
  - cudnn>=9.12.0
  - cxx-compiler
  - gcc_linux-64=13
  - git
  - gxx_linux-64=13
  - libcublas-dev
  - libcusolver-dev
  - libcusparse-dev
  - libpng
  - make
  - openssl
  - pip
  - pybind11=2.13.6
  - python=3.12
  - zlib
