name: fvdb_test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - blas=*=mkl
  - ca-certificates
  - certifi
  - cmake
  - cuda-version=13.0
  - git
  - gitpython
  - ipython
  - libpng
  - linkify-it-py
  - ninja
  - matplotlib
  - myst-parser
  - numpy
  - openssl
  - pandas
  - parameterized
  - pip>=23.3.1
  - pkg-config
  - polyscope
  - py-opencv>=4.10[build=headless*]
  - pytest-benchmark
  - python=3.12
  - pytorch-gpu=2.10.0
  - rich
  - scikit-learn
  - sphinx_rtd_theme
  - sphinx>=7.0.0
  - tensorboard
  - tqdm
  - zlib
  ## 3dgs
  - pyproj
  - scikit-image
  - torchvision
  - viser
  - ipykernel
  - nbmake
  - pip:
    - gsplat
    - pytest-markdown-docs
    - point-cloud-utils
    ## 3dgs tests
    - oiio-static-python
platforms:
  - linux-64
